### ISSUE TITLE
can't find crate for `dumpcap`

### ISSUE THREAD

**Issue by spaul13** [lukaslueg/dumpcap-rust#1]
While compiling dumpcap-rust/examples/capture_state/main.rs, I am getting the following error for creating dumpcap.

error[E0463]: can't find crate for `dumpcap`
 --> main.rs:1:1
  |
1 | extern crate dumpcap;
  | ^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

can you please tell me how to solve this?

**Comment by lukaslueg** [comment]
You execute the examples by calling `cargo run --example`; cargo will know how to compile the examples' dependencies and execute them. For example

```
cargo run --example capture_state
cargo run --example capture
cargo run --example devices
...
```

**Comment by spaul13** [comment]
but by running those examples, I can't sniff/dump any TCP packets. Can you please tell me what configurations I need to change?

**Comment by lukaslueg** [comment]
Well, they are just examples. Create a new crate and add this crate as a git-dependency. You probably want to expand on the `capture_state`-example.
